apiVersion: v1
kind: Pod
metadata:
  name: raw-server
  
  labels:
    app.kubernetes.io/name: server
spec:
  containers:
  - name: server
    image: registry.cn-shanghai.aliyuncs.com/carl-zyc/busybox:v3
    securityContext:
      capabilities:
        add:
          - NET_ADMIN
          - NET_RAW
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "64Mi"
        cpu: "250m"
    command: ["tail", "-f", "/dev/null"]